# Generated by Django 3.2 on 2021-09-27 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE'), ('N', 'PREFER NOT TO SAY')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Vital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.DecimalField(decimal_places=5, max_digits=10)),
                ('weight', models.DecimalField(decimal_places=5, max_digits=10)),
                ('bmi', models.DecimalField(decimal_places=5, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vitals', to='triage_app.patient')),
            ],
        ),
        migrations.CreateModel(
            name='VisitForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('health_status', models.CharField(choices=[('G', 'GOOD'), ('B', 'BAD')], max_length=1)),
                ('do_drugs', models.CharField(choices=[('Y', 'YES'), ('N', 'NO')], max_length=1)),
                ('patient_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_forms', to='triage_app.patient')),
            ],
        ),
    ]
