# Generated by Django 3.2 on 2021-09-27 20:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('triage_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitform',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='vital',
            name='created_at',
        ),
        migrations.AddField(
            model_name='patient',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
