# Generated by Django 3.2 on 2021-09-27 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triage_app', '0002_auto_20210927_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitform',
            name='comments',
            field=models.CharField(default='hdfsdgfsdgjfhdgjhsgjdh', max_length=1000),
            preserve_default=False,
        ),
    ]
