# Generated by Django 3.2 on 2021-09-28 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triage_app', '0003_visitform_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitform',
            old_name='do_drugs',
            new_name='on_diet',
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE'), ('N', 'NO_SAY')], max_length=1),
        ),
    ]
